name: Deploy my-app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
      
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.15.3'

    - name: Authenticate to Kubernetes cluster
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install my-app-release ./my-app --namespace default
